In [62]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer



In [63]:
with open("//Users//urvashi.//Downloads//intents.json") as f:
    content = f.readlines()
data_intents = [eval(c) for c in content]
data_intents = pd.DataFrame(data_intents)


In [64]:
data_intents.head()

id  user_id                                        tags  \
0  7544     4450                          [pause, timescale]   
1  7561     3146                  [iphone, upload, appstore]   
2  7572      142                           [debug, debugger]   
3  7599     1213  [editor, editor-launch-fail, editor-crash]   
4  7626     2218                   [animation, import, maya]   

                                             intents  \
0  [How can I pause my game?, What is the best wa...   
1  [How do I upload my iPhone app to the app stor...   
2  [Is there a way to attach a debugger to the co...   
3  [Why project indefinitely loads when opened?, ...   
4  [How can I make animations snap to a frame in ...   

                                              answer  
0  In the Editor, you can just click the pause bu...  
1  Log into Apple's developer portal and click th...  
2  You can attach the debugger to the editor proc...  
3  To attempt to solve the editor crash, create a...  
4  Set the time of AnimationState of the relevant...

In [65]:
with open("//Users//urvashi.//Downloads//raw.json") as r:
    content = r.readlines()
data_raw = [eval(d) for d in content]
data_raw = pd.DataFrame(data_raw)

In [66]:
data_raw.head()

id  user_id                                              tags  \
0  11458    44417                                           [timer]   
1  11858     2597  [editor, instantiate, editor-scripting, persist]   
2  13289     4333             [rigidbody, cube, rotatearound, roll]   
3  27760      123                              [input, unityremote]   
4  48510     5822                             [instantiate, prefab]   

    post_date  score                                              title  \
0  2019-03-23   22.0                    How to make a timer in the game   
1  2019-04-13   13.0  Programatically instantiating GameObjects to t...   
2  2021-07-10    0.0                       Rolling Cube with Rigidbody?   
3  2012-01-17    1.0  Unity Remote not sending input from iPhone or ...   
4  2011-07-13    0.0                Prefab, Instantiate, Transfer Speed   

                                            question  \
0  How to make a timer in the game? What I have s...   
1  Hello, I am working on a tile based tactics ga...   
2  Hi All, New to Unity3D, a few hours in, so bea...   
3  If I Build and Run to my iPhone4, all the inpu...   
4  prefab, Instantiate, transfer speed??? How do ...   

                                              answer  
0  This should get you started: `private var star...  
1  The syntax to create gameobjects is the same a...  
2  Here's a short Youtube video that covers exact...  
3  Stupid question, but is your mac/phone both co...  
4  Use Prefab in your Game Here is the tutorial f...

In [67]:
data_intents.head()

id  user_id                                        tags  \
0  7544     4450                          [pause, timescale]   
1  7561     3146                  [iphone, upload, appstore]   
2  7572      142                           [debug, debugger]   
3  7599     1213  [editor, editor-launch-fail, editor-crash]   
4  7626     2218                   [animation, import, maya]   

                                             intents  \
0  [How can I pause my game?, What is the best wa...   
1  [How do I upload my iPhone app to the app stor...   
2  [Is there a way to attach a debugger to the co...   
3  [Why project indefinitely loads when opened?, ...   
4  [How can I make animations snap to a frame in ...   

                                              answer  
0  In the Editor, you can just click the pause bu...  
1  Log into Apple's developer portal and click th...  
2  You can attach the debugger to the editor proc...  
3  To attempt to solve the editor crash, create a...  
4  Set the time of AnimationState of the relevant...

In [68]:
data_intents.dtypes

id          int64
user_id     int64
tags       object
intents    object
answer     object
dtype: object

In [69]:
data_intents.isnull().sum()


id         0
user_id    0
tags       0
intents    0
answer     0
dtype: int64

In [70]:
data_raw.dtypes

id             int64
user_id        int64
tags          object
post_date     object
score        float64
title         object
question      object
answer        object
dtype: object

In [71]:
data_raw.isnull().sum()

id           0
user_id      0
tags         0
post_date    0
score        4
title        0
question     0
answer       4
dtype: int64

In [72]:
data_raw.score =  data_raw.score.fillna("unknown")
data_raw.answer =  data_raw.answer.fillna("unknown")

In [73]:
data_raw.isnull().sum()

id           0
user_id      0
tags         0
post_date    0
score        0
title        0
question     0
answer       0
dtype: int64

In [76]:
# Create a CountVectorizer object
# vectorizer = CountVectorizer()

# Alternatively, create a TfidfVectorizer object (Term Frequency-Inverse Document Frequency)
vectorizer = TfidfVectorizer()
# Fit and transform the sentences
numerical_data_intents = vectorizer.fit_transform(data_intents)

In [81]:
print(numerical_data_intents.toarray())

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [78]:
numerical_data_raw = vectorizer.fit_transform(data_raw)

In [80]:
print(numerical_data_raw.toarray())

[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]]
